# Системы аутентификациии и защиты от несанкционированного доступа

Практическая работа №1

## Цель

Вывести информацию о системе компьютера

## Исходные данные

1. ОС Windows 11
2. RStudio Desktop (v.2023.03.0+386)
3. Интерпретатор языка R (v.4.2.2)
4. PowerShell 

## План

**Вариант 1 - С помощью языка R**
1. Отобразить системную и пользовательскую информацию
2. Отобразить всю информацию о системе Windows
3. Отобразить информацию о процессоре
4. Отобразить логи системы

**Вариант 2 - При помощи PowerShell**
1. Отобразить полную версию Windows
2. Отобразить сведения о процессоре
3. Отобразить логи системы

## Шаги

**Вариант 1**

1. Команда `Sys.info()` cообщает системную и пользовательскую информацию.

```
Sys.info()
```

2. Команда `system2(“systeminfo”, stdout = TRUE)` выводит всю информацию о системе Windows.

```
system2(“systeminfo”, stdout = TRUE)
```

3.  Команда `system(“wmic cpu get name”)` выводит информацию о процессоре

```
system2("cmd", args = c("/c", "wmic cpu get name"), stdout = TRUE)
```

4. Команда `system(“powershell.exe”, args = c(“Get-EventLog”, “-LogName”, “System”, “-Newest”, “30”), stdout = TRUE)` выводит информацию о логах

```
system2("powershell.exe", args = c("Get-EventLog", "-LogName", "System", "-Newest", "30"), stdout = TRUE)
```

**Вариант 2 - PowerShell**

1. Команда `(Get-ItemProperty -Path c:\windows\system32\hal.dll).VersionInfo.FileVersion` выдет полную версию Windows (включая номер редакции/сборки)

```
(Get-ItemProperty -Path c:\windows\system32\hal.dll).VersionInfo.FileVersion
```

2. Чтобы получить сведения о процессоре используем команду `Get-WmiObject win32_Processor`

```
Get-WmiObject win32_Processor
```

3. Для получения логов системы используем команду `Get-EventLog -LogName 'system' -Newest 30`

```
Get-EventLog -LogName 'system' -Newest 30
```

## Оценка результатов
Был произведен анализ основных технических характеристик операционной системы, процессора и логов системы.
 
## Вывод
В ходе выполнения практической работы были изучены возможности языка программирования R и командной оболочки PowerShell, что позволило приобрести опыт работы с синтаксисом R.
